### ISSUE TITLE
Gulp v4 compatibility issues

### ISSUE THREAD

**Issue by milkice233** [giuem/uptimerobot-page#145]
Some guys reported that an error occurred during `gulp build` which said 'Task function must be specified.'. https://github.com/gulpjs/undertaker/issues/54 indicates that gulpfile.js must be updated in order to be compatible with gulp v4.

**Comment by giuem** [comment]
But this project is using v3.9.1. (see [package.json](https://github.com/giuem/uptimerobot-page/blob/master/package.json#L60)).

**Comment by milkice233** [comment]
Hmm.. That's right.
But I can't figure out why `npm install` installs a wrong version of gulp without respecting the version in `package.json`(3.9.1). Anyhow, I've come out with a workaround and seems to be working well, thus this issue shall be closed.
